error: Use formatSyntaxKind throughout
So e.g. we say "tsflower-unimplemented: TypePredicate" instead of the
rather less helpful "tsflower-unimplemented: FirstTypeNode".