error: Take a description in crudeError
Still never as good as a nice, structured, marked-in-output error; but
this at least means there's no longer any reason to go for throwing an
exception directly, and therefore to give up on the input-source location.